# Generated by Django 2.0.2 on 2019-09-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190927_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='person',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
