# Generated by Django 2.0.2 on 2019-09-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190927_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketer',
            name='t_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
